/*CRIA GENERATOR PARA O CAMPO ID USUARIO*/
CREATE GENERATOR GEN_ID_USUARIO;

/*CRIA TRIGGER´S PARA USUARIO*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_USUARIO FOR USUARIO ACTIVE
 BEFORE INSERT POSITION 0
 
AS 
BEGIN 
    NEW.ID_USUARIO=gen_id(GEN_ID_USUARIO,1);
END^

SET TERM ; ^


INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES('LUIS','123','ADM','13.03.2023');

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES('PAULO','123','ADM','13.03.2023');

INSERT INTO USUARIO(NOME,SENHA,TIPO,CADASTRO)
VALUES('PEDRO','123','ADM','13.03.2023');
SELECT *FROM USUARIO

/*CRIA TRIGGER E GENERATOR PARA CLIENTE*/


CREATE GENERATOR GEN_ID_CLIENTE;

/*CRIA TRIGGER´S PARA CLIENTE*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_CLIENTE FOR CLIENTE ACTIVE
 BEFORE INSERT POSITION 0
 
AS 
BEGIN 
    NEW.ID_CLIENTE=gen_id(GEN_ID_CLIENTE,1);
END^

SET TERM ; ^
/**INSERE REGISTRO NA TABELA CLIENTE */
INSERT INTO CLIENTE (NOME,ENDERECO,NUMERO,BAIRRO,CIDADE,UF,CEP,TELEFONE,
CPF,EMAIL,CADASTRO) VALUES('MARCIO','AV.DR.SORES DE OLIVVEIRA','233','GUANABARA','ITUVERAVA','SP','14.500-000',
'169999-9999','44444444','RT@GMAIL.COM','02.05.2022');
/*SELECT*FROM CLIENTE */


/*--------------------------EMPRESA------------------------------*/
/*CRIA O GENERATOR PARA EMPRESA*/
CREATE GENERATOR GEN_ID_EMPRESA;

/*CRIA A TRIGGER PARA EMPRESA*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_EMPRESA FOR EMPRESA ACTIVE
 BEFORE INSERT POSITION 0
 
AS 
BEGIN 
    NEW.ID_EMPRESA=gen_id(GEN_ID_EMPRESA,1);
END^

SET TERM ; 
/*-----------------------------FORNECEDORES---------------------*/
/*CRIA O GENERATOR PARA FORNECEDOR*/
CREATE GENERATOR GEN_ID_FORNECEDOR;

/*CRIA A TRIGGER PARA A TABELA FORNECEDORES*/
SET TERM ^ ;

CREATE TRIGGER INSERE_ID_FONECEDOR FOR FORNECEDOR ACTIVE
 BEFORE INSERT POSITION 0
 
AS 
BEGIN 
    NEW.ID_FORNECEDOR=gen_id(GEN_ID_FORNECEDOR,1);
END^

SET TERM ; 

/*------------------------PRODUTO----------------------------*/
/*CRIA O GENERATOR PRODUTO*/
CREATE GENERATOR GEN_ID_PRODUTO;
/*CRIA A TRIGGER PARA PRODUTO*/
SET TERM ^;

CREATE TRIGGER INSERE_ID_PRODUTO FOR PRODUTO ACTIVE
before insert position 0

AS
begin
    NEW.ID_PRODUTO=gen_id(GEN_ID_PRODUTO,1);
END^

SET TERM ;
/*------------------------FORMA DE PAGAMENTO----------------------------*/
/*CRIA O GENERATOR FORMA DE PAGAMENTO*/
CREATE GENERATOR GEN_ID_FORMA_PAGTO;
/*CRIA A TRIGGER PARA FORMA DE PAGAMENTO*/
SET TERM ^;

CREATE TRIGGER INSERE_ID_FORMA_PAGTO FOR FORMA_PAGTO ACTIVE
before insert position 0

AS
begin
    NEW.ID_FORMA_PAGTO=gen_id(GEN_ID_FORMA_PAGTO,1);
END^

SET TERM ;
/*-----------------------COMPRAS----------------------------*/
/*CRIA O GENERATOR FORMA DE PAGAMENTO*/
CREATE GENERATOR GEN_ID_COMPRA
/*CRIA A TRIGGER PARA COMPRAS*/
SET TERM ^;

CREATE TRIGGER INSERE_ID_COMPRA FOR COMPRA ACTIVE
before insert position 0

AS
begin
    NEW.ID_COMPRA=gen_id(GEN_ID_COMPRA,1);
END^

SET TERM ;
/*------------------------VENDAS----------------------------*/
/*CRIA O GENERATOR VENDAS*/
CREATE GENERATOR GEN_ID_VENDA;
/*CRIA A TRIGGER PARA FORMA DE PAGAMENTO*/
SET TERM ^;

CREATE TRIGGER INSERE_ID_VENDA FOR VENDA ACTIVE
before insert position 0

AS
begin
    NEW.ID_VENDA=gen_id(GEN_ID_VENDA,1);
END^

SET TERM ;




